name: Build Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Create env file
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: ".env.production.local"
          # Uses base 64 to allow new lines.
          FILE_BASE64: "VlVFX0FQUF9CQVNFX1VSTD1odHRwczovL3BvbHl0b3BpYS5mdW4KVlVFX0FQUF9ESVNDT1JEX0NMSUVOVF9JRD04MjI0MzYxODA0MzkyMDM4NjEKVlVFX0FQUF9BUElfVVJMPWh0dHBzOi8vcG9seW1waWNzLmhlcm9rdWFwcC5jb20K"

      - name: Install and Build
        run: |
            npm install
            npm run build
            cp dist/index.html dist/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: build
          folder: dist
